# *****  This is the user defined part of the Makefile

# The directory where the examples reside (you HAVE to change this)
# PACS directories
PACS_ROOT = /home/fpettenon/PACS/pacs-examples
PACS_INC_DIR = $(PACS_ROOT)/Examples/src/Utilities
PACS_EXTRAS_DIR = $(PACS_ROOT)/Extras
PACS_MUPARSER_DIR = $(PACS_EXTRAS_DIR)/muparser/include/
PACS_JSON_DIR = $(PACS_EXTRAS_DIR)/json/include/nlohmann/
PACS_LIB_DIR = $(PACS_ROOT)/Examples/lib
